In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity ="all"

#  List practice

In [8]:
my_list=[20,30,40,50,60,22,43]
my_list[0:4:3]

[20, 50]

In [9]:
x=[1,"b",3]
x

[1, 'b', 3]

In [15]:
 dict={"Sub":"Graduate","Asher":"Baby Boy","Binesh":"IOS developer",3:"Family member"}
dict["Sub"]
dict.keys()
dict.values()

'Graduate'

dict_keys(['Sub', 'Asher', 'Binesh', 3])

dict_values(['Graduate', 'Baby Boy', 'IOS developer', 'Family member'])

In [18]:
student ={"s1":["IBM"],"s2":["Infy","Tcs","Wipro"]}
student["s2"][1]

'Tcs'

In [21]:
tuple =(1,2,3,4)
list=[1,2,3,4]
list.append(6)
list
tuple.count(1)

[1, 2, 3, 4, 6]

1

# Pandas practice

In [22]:
 #pandas
import pandas as pd
df=pd.read_csv("My Uber Drives 2016.csv")

In [135]:
#dataframe
df

START_DATE*         END_DATE* CATEGORY*            START*  \
0       1/1/2016 21:11    1/1/2016 21:17  Business       Fort Pierce   
1        1/2/2016 1:25     1/2/2016 1:37  Business       Fort Pierce   
2       1/2/2016 20:25    1/2/2016 20:38  Business       Fort Pierce   
3       1/5/2016 17:31    1/5/2016 17:45  Business       Fort Pierce   
4       1/6/2016 14:42    1/6/2016 15:49  Business       Fort Pierce   
...                ...               ...       ...               ...   
1151  12/31/2016 13:24  12/31/2016 13:42  Business           Kar?chi   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1153  12/31/2016 21:32  12/31/2016 21:50  Business        Katunayake   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*         PURPOSE*   Miles_cat  MY_year  
0          Fort Pierce      5.1   Meal/Entertain   Long Trip     2000  
1          Fort Pierce      5.0              NaN  Short Trip     2000  
2          Fort Pierce      4.8  Errand/Supplies  Short Trip     2000  
3          Fort Pierce      4.7          Meeting  Short Trip     2000  
4      West Palm Beach     63.7   Customer Visit   Long Trip     2000  
...                ...      ...              ...         ...      ...  
1151  Unknown Location      3.9   Temporary Site  Short Trip     2000  
1152  Unknown Location     16.2          Meeting   Long Trip     2000  
1153           Gampaha      6.4   Temporary Site   Long Trip     2000  
1154         Ilukwatta     48.2   Temporary Site   Long Trip     2000  
1155               NaN  12204.7              NaN   Long Trip     2000  

[1156 rows x 9 columns]

In [187]:
df["START_DATE*"]

0      2016-01-01 21:11:00
1      2016-01-02 01:25:00
2      2016-01-02 20:25:00
3      2016-01-05 17:31:00
4      2016-01-06 14:42:00
               ...        
1148   2016-12-30 16:45:00
1149   2016-12-30 23:06:00
1150   2016-12-31 01:07:00
1151   2016-12-31 13:24:00
1152   2016-12-31 15:03:00
Name: START_DATE*, Length: 1153, dtype: datetime64[ns]

In [199]:
df["MILES*"]

0        5.1
1        5.0
2        4.8
3        4.7
4       63.7
        ... 
1148     4.6
1149     0.8
1150     0.7
1151     3.9
1152    16.2
Name: MILES*, Length: 1153, dtype: float64

In [24]:
type(df)

pandas.core.frame.DataFrame

In [25]:
df.dtypes

START_DATE*     object
END_DATE*       object
CATEGORY*       object
START*          object
STOP*           object
MILES*         float64
PURPOSE*        object
dtype: object

In [28]:
df.head(n=10)

START_DATE*        END_DATE* CATEGORY*           START*  \
0   1/1/2016 21:11   1/1/2016 21:17  Business      Fort Pierce   
1    1/2/2016 1:25    1/2/2016 1:37  Business      Fort Pierce   
2   1/2/2016 20:25   1/2/2016 20:38  Business      Fort Pierce   
3   1/5/2016 17:31   1/5/2016 17:45  Business      Fort Pierce   
4   1/6/2016 14:42   1/6/2016 15:49  Business      Fort Pierce   
5   1/6/2016 17:15   1/6/2016 17:19  Business  West Palm Beach   
6   1/6/2016 17:30   1/6/2016 17:35  Business  West Palm Beach   
7   1/7/2016 13:27   1/7/2016 13:33  Business             Cary   
8   1/10/2016 8:05   1/10/2016 8:25  Business             Cary   
9  1/10/2016 12:17  1/10/2016 12:44  Business          Jamaica   

             STOP*  MILES*         PURPOSE*  
0      Fort Pierce     5.1   Meal/Entertain  
1      Fort Pierce     5.0              NaN  
2      Fort Pierce     4.8  Errand/Supplies  
3      Fort Pierce     4.7          Meeting  
4  West Palm Beach    63.7   Customer Visit  
5  West Palm Beach     4.3   Meal/Entertain  
6       Palm Beach     7.1          Meeting  
7             Cary     0.8          Meeting  
8      Morrisville     8.3          Meeting  
9         New York    16.5   Customer Visit

In [29]:
df.shape

(1156, 7)

In [30]:
df.tail()

START_DATE*         END_DATE* CATEGORY*            START*  \
1151  12/31/2016 13:24  12/31/2016 13:42  Business           Kar?chi   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1153  12/31/2016 21:32  12/31/2016 21:50  Business        Katunayake   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*        PURPOSE*  
1151  Unknown Location      3.9  Temporary Site  
1152  Unknown Location     16.2         Meeting  
1153           Gampaha      6.4  Temporary Site  
1154         Ilukwatta     48.2  Temporary Site  
1155               NaN  12204.7             NaN

In [32]:
temp = pd.DataFrame({"a":["1","2","3"],"b":[1,2,3],"c":["12-09-2012","13-08-2023","23-12-2019"]})
temp
temp.dtypes

a  b           c
0  1  1  12-09-2012
1  2  2  13-08-2023
2  3  3  23-12-2019

a    object
b     int64
c    object
dtype: object

In [38]:
temp['c']=pd.to_datetime(temp['c'])
temp.dtypes
temp

a            object
b             int64
c    datetime64[ns]
dtype: object

a  b          c
0  1  1 2012-12-09
1  2  2 2023-08-13
2  3  3 2019-12-23

In [42]:
temp["a"]=pd.to_numeric(temp['a'])
temp.dtypes

a             int64
b             int64
c    datetime64[ns]
dtype: object

In [35]:
pd.to_datetime(["2016-june-02","2021-jan-21"])

DatetimeIndex(['2016-06-02', '2021-01-21'], dtype='datetime64[ns]', freq=None)

In [39]:
pd.to_datetime(["2016-sep-11","abs"], errors="coerce" )

DatetimeIndex(['2016-09-11', 'NaT'], dtype='datetime64[ns]', freq=None)

In [44]:
df.describe(include="all")

START_DATE*        END_DATE* CATEGORY* START* STOP*        MILES*  \
count              1156             1155      1155   1155  1155   1156.000000   
unique             1155             1154         2    177   188           NaN   
top     6/28/2016 23:34  6/28/2016 23:59  Business   Cary  Cary           NaN   
freq                  2                2      1078    201   203           NaN   
mean                NaN              NaN       NaN    NaN   NaN     21.115398   
std                 NaN              NaN       NaN    NaN   NaN    359.299007   
min                 NaN              NaN       NaN    NaN   NaN      0.500000   
25%                 NaN              NaN       NaN    NaN   NaN      2.900000   
50%                 NaN              NaN       NaN    NaN   NaN      6.000000   
75%                 NaN              NaN       NaN    NaN   NaN     10.400000   
max                 NaN              NaN       NaN    NaN   NaN  12204.700000   

       PURPOSE*  
count       653  
unique       10  
top     Meeting  
freq        187  
mean        NaN  
std         NaN  
min         NaN  
25%         NaN  
50%         NaN  
75%         NaN  
max         NaN

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   START_DATE*  1156 non-null   object 
 1   END_DATE*    1155 non-null   object 
 2   CATEGORY*    1155 non-null   object 
 3   START*       1155 non-null   object 
 4   STOP*        1155 non-null   object 
 5   MILES*       1156 non-null   float64
 6   PURPOSE*     653 non-null    object 
dtypes: float64(1), object(6)
memory usage: 63.3+ KB


In [48]:
df["START*"].value_counts().head()

Cary                201
Unknown Location    148
Morrisville          85
Whitebridge          68
Islamabad            57
Name: START*, dtype: int64

# Common data manipulation task

In [54]:
#selecting /indexing
#iloc- accessing the data using positional index
df.iloc[0:5,0:4]
df.iloc[0:5,[0,3]]
df.iloc[0:4]
sub=df.iloc[:,:-1]
sub.shape
df.shape

START_DATE*       END_DATE* CATEGORY*       START*
0  1/1/2016 21:11  1/1/2016 21:17  Business  Fort Pierce
1   1/2/2016 1:25   1/2/2016 1:37  Business  Fort Pierce
2  1/2/2016 20:25  1/2/2016 20:38  Business  Fort Pierce
3  1/5/2016 17:31  1/5/2016 17:45  Business  Fort Pierce
4  1/6/2016 14:42  1/6/2016 15:49  Business  Fort Pierce

START_DATE*       START*
0  1/1/2016 21:11  Fort Pierce
1   1/2/2016 1:25  Fort Pierce
2  1/2/2016 20:25  Fort Pierce
3  1/5/2016 17:31  Fort Pierce
4  1/6/2016 14:42  Fort Pierce

START_DATE*       END_DATE* CATEGORY*       START*        STOP*  MILES*  \
0  1/1/2016 21:11  1/1/2016 21:17  Business  Fort Pierce  Fort Pierce     5.1   
1   1/2/2016 1:25   1/2/2016 1:37  Business  Fort Pierce  Fort Pierce     5.0   
2  1/2/2016 20:25  1/2/2016 20:38  Business  Fort Pierce  Fort Pierce     4.8   
3  1/5/2016 17:31  1/5/2016 17:45  Business  Fort Pierce  Fort Pierce     4.7   

          PURPOSE*  
0   Meal/Entertain  
1              NaN  
2  Errand/Supplies  
3          Meeting

(1156, 6)

(1156, 7)

In [57]:
#loc:label based indexing
df.loc[:,["START*","STOP*"]]
df[["START*","STOP*"]]

START*             STOP*
0          Fort Pierce       Fort Pierce
1          Fort Pierce       Fort Pierce
2          Fort Pierce       Fort Pierce
3          Fort Pierce       Fort Pierce
4          Fort Pierce   West Palm Beach
...                ...               ...
1151           Kar?chi  Unknown Location
1152  Unknown Location  Unknown Location
1153        Katunayake           Gampaha
1154           Gampaha         Ilukwatta
1155               NaN               NaN

[1156 rows x 2 columns]

START*             STOP*
0          Fort Pierce       Fort Pierce
1          Fort Pierce       Fort Pierce
2          Fort Pierce       Fort Pierce
3          Fort Pierce       Fort Pierce
4          Fort Pierce   West Palm Beach
...                ...               ...
1151           Kar?chi  Unknown Location
1152  Unknown Location  Unknown Location
1153        Katunayake           Gampaha
1154           Gampaha         Ilukwatta
1155               NaN               NaN

[1156 rows x 2 columns]

In [69]:
ser=df.loc[:,"START*"]
type(ser)
df.loc[:,["START*"]].head()

pandas.core.series.Series

START*
0  Fort Pierce
1  Fort Pierce
2  Fort Pierce
3  Fort Pierce
4  Fort Pierce

In [68]:
df.loc[0:4,["START_DATE*","MILES*"]]

START_DATE*  MILES*
0  1/1/2016 21:11     5.1
1   1/2/2016 1:25     5.0
2  1/2/2016 20:25     4.8
3  1/5/2016 17:31     4.7
4  1/6/2016 14:42    63.7

In [65]:
df.loc[:,("START*","STOP*")]

START*             STOP*
0          Fort Pierce       Fort Pierce
1          Fort Pierce       Fort Pierce
2          Fort Pierce       Fort Pierce
3          Fort Pierce       Fort Pierce
4          Fort Pierce   West Palm Beach
...                ...               ...
1151           Kar?chi  Unknown Location
1152  Unknown Location  Unknown Location
1153        Katunayake           Gampaha
1154           Gampaha         Ilukwatta
1155               NaN               NaN

[1156 rows x 2 columns]

In [70]:
df.columns

Index(['START_DATE*', 'END_DATE*', 'CATEGORY*', 'START*', 'STOP*', 'MILES*',
       'PURPOSE*'],
      dtype='object')

# Filtering


In [77]:
df["MILES*"]>10
df2=df.loc[df["MILES*"]>10,["START_DATE*","MILES*"]]
df2.head()
df[df["MILES*"]>10]

0       False
1       False
2       False
3       False
4        True
        ...  
1151    False
1152     True
1153    False
1154     True
1155     True
Name: MILES*, Length: 1156, dtype: bool

START_DATE*  MILES*
4    1/6/2016 14:42    63.7
9   1/10/2016 12:17    16.5
10  1/10/2016 15:08    10.8
22  1/12/2016 16:02    15.1
23  1/13/2016 13:54    11.2

START_DATE*         END_DATE* CATEGORY*            START*  \
4       1/6/2016 14:42    1/6/2016 15:49  Business       Fort Pierce   
9      1/10/2016 12:17   1/10/2016 12:44  Business           Jamaica   
10     1/10/2016 15:08   1/10/2016 15:51  Business          New York   
22     1/12/2016 16:02   1/12/2016 17:00  Business          New York   
23     1/13/2016 13:54   1/13/2016 14:07  Business          Downtown   
...                ...               ...       ...               ...   
1134  12/29/2016 11:28  12/29/2016 12:00  Business  Unknown Location   
1144  12/29/2016 23:14  12/29/2016 23:47  Business  Unknown Location   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*        PURPOSE*  
4      West Palm Beach     63.7  Customer Visit  
9             New York     16.5  Customer Visit  
10              Queens     10.8         Meeting  
22       Queens County     15.1         Meeting  
23             Gulfton     11.2         Meeting  
...                ...      ...             ...  
1134           Kar?chi     11.9  Meal/Entertain  
1144           Kar?chi     12.9         Meeting  
1152  Unknown Location     16.2         Meeting  
1154         Ilukwatta     48.2  Temporary Site  
1155               NaN  12204.7             NaN  

[316 rows x 7 columns]

In [81]:
df.loc[df["START*"]=="New York",["MILES*"]].head()

MILES*
10     10.8
22     15.1
106    13.0
423    16.3

In [83]:
rides=df[df["START*"].isin(["Cary","New York"])]
rides.head(n=10)

START_DATE*        END_DATE* CATEGORY*    START*          STOP*  \
7    1/7/2016 13:27   1/7/2016 13:33  Business      Cary           Cary   
8    1/10/2016 8:05   1/10/2016 8:25  Business      Cary    Morrisville   
10  1/10/2016 15:08  1/10/2016 15:51  Business  New York         Queens   
22  1/12/2016 16:02  1/12/2016 17:00  Business  New York  Queens County   
28  1/15/2016 11:43  1/15/2016 12:03  Business      Cary         Durham   
30  1/18/2016 14:55  1/18/2016 15:06  Business      Cary           Cary   
34  1/20/2016 10:36  1/20/2016 11:11  Business      Cary        Raleigh   
37  1/21/2016 14:25  1/21/2016 14:29  Business      Cary           Cary   
38  1/21/2016 14:43  1/21/2016 14:51  Business      Cary           Cary   
39  1/21/2016 16:01  1/21/2016 16:06  Business      Cary           Cary   

    MILES*         PURPOSE*  
7      0.8          Meeting  
8      8.3          Meeting  
10    10.8          Meeting  
22    15.1          Meeting  
28    10.4   Meal/Entertain  
30     4.8   Meal/Entertain  
34    17.1          Meeting  
37     1.6  Errand/Supplies  
38     2.4   Meal/Entertain  
39     1.0   Meal/Entertain

In [108]:
# df.loc[df["MILES*"]>10,["START_DATE*","MILES*"]]
df3=df[(df["MILES*"]>10) & (df["START*"].isin(["Cary","New York"]))].head(n=10)
df3.reset_index(inplace=True,drop=True)
# implace to chance the original data frame, drop for droping the old index column
df3
# df4

START_DATE*        END_DATE* CATEGORY*    START*          STOP*  \
0  1/10/2016 15:08  1/10/2016 15:51  Business  New York         Queens   
1  1/12/2016 16:02  1/12/2016 17:00  Business  New York  Queens County   
2  1/15/2016 11:43  1/15/2016 12:03  Business      Cary         Durham   
3  1/20/2016 10:36  1/20/2016 11:11  Business      Cary        Raleigh   
4  1/27/2016 10:19  1/27/2016 10:48  Business      Cary        Raleigh   
5  1/28/2016 12:28  1/28/2016 13:00  Business      Cary        Raleigh   
6  1/29/2016 11:43  1/29/2016 12:03  Business      Cary         Durham   
7   2/1/2016 10:35   2/1/2016 11:15  Business      Cary    Chapel Hill   
8   2/5/2016 11:47   2/5/2016 12:07  Business      Cary         Durham   
9   2/6/2016 16:20   2/6/2016 16:53  Business      Cary        Raleigh   

   MILES*         PURPOSE*  
0    10.8          Meeting  
1    15.1          Meeting  
2    10.4   Meal/Entertain  
3    17.1          Meeting  
4    18.7   Customer Visit  
5    19.0   Temporary Site  
6    10.4          Meeting  
7    19.4   Customer Visit  
8    10.4          Meeting  
9    11.4  Between Offices

# Sorting

In [112]:
df.sort_values(by = ["MILES*"], ascending=False).head()

START_DATE*         END_DATE* CATEGORY*            START*  \
1155            Totals               NaN       NaN               NaN   
269    3/25/2016 16:52   3/25/2016 22:22  Business             Latta   
270    3/25/2016 22:54    3/26/2016 1:39  Business      Jacksonville   
881   10/30/2016 15:22  10/30/2016 18:23  Business         Asheville   
776    9/27/2016 21:01    9/28/2016 2:37  Business  Unknown Location   

                 STOP*   MILES*        PURPOSE*  
1155               NaN  12204.7             NaN  
269       Jacksonville    310.3  Customer Visit  
270          Kissimmee    201.0         Meeting  
881             Mebane    195.9             NaN  
776   Unknown Location    195.6             NaN

In [119]:
df.sort_values(by=["START*","MILES*"],ascending=[True,False]).head(n=10)

START_DATE*         END_DATE* CATEGORY*  START*          STOP*  \
906    11/4/2016 21:04   11/4/2016 21:20  Business   Agnew           Cory   
911    11/6/2016 10:50   11/6/2016 11:04  Business   Agnew    Renaissance   
908     11/5/2016 8:34    11/5/2016 8:43  Business   Agnew    Renaissance   
910    11/5/2016 19:20   11/5/2016 19:28  Business   Agnew          Agnew   
879   10/30/2016 12:58  10/30/2016 13:18  Business  Almond    Bryson City   
1001  11/26/2016 17:36  11/26/2016 17:56  Business    Apex  Holly Springs   
1033   12/9/2016 13:15   12/9/2016 13:43  Business    Apex           Cary   
410     6/6/2016 21:08    6/6/2016 21:37  Business    Apex           Cary   
647    8/10/2016 19:47   8/10/2016 20:02  Business    Apex           Cary   
60     1/30/2016 18:09   1/30/2016 18:24  Business    Apex           Cary   

      MILES*        PURPOSE*  
906      4.3             NaN  
911      2.4             NaN  
908      2.2             NaN  
910      2.2             NaN  
879     15.2             NaN  
1001     9.0         Meeting  
1033     8.8  Temporary Site  
410      7.2  Meal/Entertain  
647      6.0             NaN  
60       5.7  Customer Visit

# Conditionally adding column

In [133]:
import numpy as np
df["Miles_cat"]=np.where(df["MILES*"] >5,"Long Trip","Short Trip") 
df.head(n=10)

START_DATE*        END_DATE* CATEGORY*           START*  \
0   1/1/2016 21:11   1/1/2016 21:17  Business      Fort Pierce   
1    1/2/2016 1:25    1/2/2016 1:37  Business      Fort Pierce   
2   1/2/2016 20:25   1/2/2016 20:38  Business      Fort Pierce   
3   1/5/2016 17:31   1/5/2016 17:45  Business      Fort Pierce   
4   1/6/2016 14:42   1/6/2016 15:49  Business      Fort Pierce   
5   1/6/2016 17:15   1/6/2016 17:19  Business  West Palm Beach   
6   1/6/2016 17:30   1/6/2016 17:35  Business  West Palm Beach   
7   1/7/2016 13:27   1/7/2016 13:33  Business             Cary   
8   1/10/2016 8:05   1/10/2016 8:25  Business             Cary   
9  1/10/2016 12:17  1/10/2016 12:44  Business          Jamaica   

             STOP*  MILES*         PURPOSE*   Miles_cat  MY_year  
0      Fort Pierce     5.1   Meal/Entertain   Long Trip     2000  
1      Fort Pierce     5.0              NaN  Short Trip     2000  
2      Fort Pierce     4.8  Errand/Supplies  Short Trip     2000  
3      Fort Pierce     4.7          Meeting  Short Trip     2000  
4  West Palm Beach    63.7   Customer Visit   Long Trip     2000  
5  West Palm Beach     4.3   Meal/Entertain  Short Trip     2000  
6       Palm Beach     7.1          Meeting   Long Trip     2000  
7             Cary     0.8          Meeting  Short Trip     2000  
8      Morrisville     8.3          Meeting   Long Trip     2000  
9         New York    16.5   Customer Visit   Long Trip     2000

In [139]:
df["MY_year"]=np.array(2000)
df

START_DATE*         END_DATE* CATEGORY*            START*  \
0       1/1/2016 21:11    1/1/2016 21:17  Business       Fort Pierce   
1        1/2/2016 1:25     1/2/2016 1:37  Business       Fort Pierce   
2       1/2/2016 20:25    1/2/2016 20:38  Business       Fort Pierce   
3       1/5/2016 17:31    1/5/2016 17:45  Business       Fort Pierce   
4       1/6/2016 14:42    1/6/2016 15:49  Business       Fort Pierce   
...                ...               ...       ...               ...   
1151  12/31/2016 13:24  12/31/2016 13:42  Business           Kar?chi   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1153  12/31/2016 21:32  12/31/2016 21:50  Business        Katunayake   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*         PURPOSE*   Miles_cat  MY_year  
0          Fort Pierce      5.1   Meal/Entertain   Long Trip     2000  
1          Fort Pierce      5.0              NaN  Short Trip     2000  
2          Fort Pierce      4.8  Errand/Supplies  Short Trip     2000  
3          Fort Pierce      4.7          Meeting  Short Trip     2000  
4      West Palm Beach     63.7   Customer Visit   Long Trip     2000  
...                ...      ...              ...         ...      ...  
1151  Unknown Location      3.9   Temporary Site  Short Trip     2000  
1152  Unknown Location     16.2          Meeting   Long Trip     2000  
1153           Gampaha      6.4   Temporary Site   Long Trip     2000  
1154         Ilukwatta     48.2   Temporary Site   Long Trip     2000  
1155               NaN  12204.7              NaN   Long Trip     2000  

[1156 rows x 9 columns]

In [124]:
df["Miles_cat"]=np.where(df["MILES*"] <5,"Short Trip",np.where(df["MILES*"]>20,"Long Trip","Medium Trip")) 
df

START_DATE*         END_DATE* CATEGORY*            START*  \
0       1/1/2016 21:11    1/1/2016 21:17  Business       Fort Pierce   
1        1/2/2016 1:25     1/2/2016 1:37  Business       Fort Pierce   
2       1/2/2016 20:25    1/2/2016 20:38  Business       Fort Pierce   
3       1/5/2016 17:31    1/5/2016 17:45  Business       Fort Pierce   
4       1/6/2016 14:42    1/6/2016 15:49  Business       Fort Pierce   
...                ...               ...       ...               ...   
1151  12/31/2016 13:24  12/31/2016 13:42  Business           Kar?chi   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   
1153  12/31/2016 21:32  12/31/2016 21:50  Business        Katunayake   
1154  12/31/2016 22:08  12/31/2016 23:51  Business           Gampaha   
1155            Totals               NaN       NaN               NaN   

                 STOP*   MILES*         PURPOSE*    Miles_cat  MY_year  
0          Fort Pierce      5.1   Meal/Entertain  Medium Trip     2000  
1          Fort Pierce      5.0              NaN  Medium Trip     2000  
2          Fort Pierce      4.8  Errand/Supplies   Short Trip     2000  
3          Fort Pierce      4.7          Meeting   Short Trip     2000  
4      West Palm Beach     63.7   Customer Visit    Long Trip     2000  
...                ...      ...              ...          ...      ...  
1151  Unknown Location      3.9   Temporary Site   Short Trip     2000  
1152  Unknown Location     16.2          Meeting  Medium Trip     2000  
1153           Gampaha      6.4   Temporary Site  Medium Trip     2000  
1154         Ilukwatta     48.2   Temporary Site    Long Trip     2000  
1155               NaN  12204.7              NaN    Long Trip     2000  

[1156 rows x 9 columns]

# grouping

In [126]:
df.groupby("START*")["MILES*"].agg("mean")
# group by start and show the mean of miles corresponding
# df.groupby("START*")["MILES*"].mean()

START*
Agnew                2.775000
Almond              15.200000
Apex                 5.341176
Arabi               17.000000
Arlington            4.900000
                      ...    
West University      2.200000
Weston               4.000000
Westpark Place       2.182353
Whitebridge          4.020588
Winston Salem      133.600000
Name: MILES*, Length: 177, dtype: float64

In [144]:
df.drop(["MY_year"], axis=1,inplace=True)

In [145]:
df.groupby("START*").mean()

C:\Users\subit\AppData\Local\Temp\ipykernel_12700\564090668.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby("START*").mean()


MILES*
START*                     
Agnew              2.775000
Almond            15.200000
Apex               5.341176
Arabi             17.000000
Arlington          4.900000
...                     ...
West University    2.200000
Weston             4.000000
Westpark Place     2.182353
Whitebridge        4.020588
Winston Salem    133.600000

[177 rows x 1 columns]

In [150]:
sub=df.groupby(["START*","STOP*"]).agg(["mean","sum"]).head(20)
sub

C:\Users\subit\AppData\Local\Temp\ipykernel_12700\3244111869.py:1: FutureWarning: ['START_DATE*', 'END_DATE*', 'CATEGORY*', 'PURPOSE*', 'Miles_cat'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  sub=df.groupby(["START*","STOP*"]).agg(["mean","sum"]).head(20)


MILES*       
                                                           mean    sum
START*                    STOP*                                       
Agnew                     Agnew                        2.200000    2.2
                          Cory                         4.300000    4.3
                          Renaissance                  2.300000    4.6
Almond                    Bryson City                 15.200000   15.2
Apex                      Apex                         2.150000    4.3
                          Cary                         5.792308   75.3
                          Eagle Rock                   2.200000    2.2
                          Holly Springs                9.000000    9.0
Arabi                     Metairie                    17.000000   17.0
Arlington                 Washington                   4.900000    4.9
Arlington Park at Amberly Lexington Park at Amberly    1.300000    1.3
Asheville                 Mebane                     195.900000  195.9
                          Topton                      91.800000   91.8
Austin                    Katy                       136.000000  136.0
Banner Elk                Banner Elk                   6.680000   33.4
                          Boone                       15.100000   15.1
                          Elk Park                    22.400000   22.4
                          Newland                     28.100000   28.1
Bellevue                  Seattle                     12.900000   12.9
Berkeley                  El Cerrito                   2.300000    2.3

In [151]:
df.dtypes

START_DATE*     object
END_DATE*       object
CATEGORY*       object
START*          object
STOP*           object
MILES*         float64
PURPOSE*        object
Miles_cat       object
dtype: object

In [157]:
df=df.iloc[:-1,:]
df.tail()
df["START_DATE*"] =pd.to_datetime(df["START_DATE*"])
df.dtypes

START_DATE*         END_DATE* CATEGORY*            START*  \
1148  12/30/2016 16:45  12/30/2016 17:08  Business           Kar?chi   
1149  12/30/2016 23:06  12/30/2016 23:10  Business           Kar?chi   
1150   12/31/2016 1:07   12/31/2016 1:14  Business           Kar?chi   
1151  12/31/2016 13:24  12/31/2016 13:42  Business           Kar?chi   
1152  12/31/2016 15:03  12/31/2016 15:38  Business  Unknown Location   

                 STOP*  MILES*        PURPOSE*   Miles_cat  
1148           Kar?chi     4.6         Meeting  Short Trip  
1149           Kar?chi     0.8  Customer Visit  Short Trip  
1150           Kar?chi     0.7         Meeting  Short Trip  
1151  Unknown Location     3.9  Temporary Site  Short Trip  
1152  Unknown Location    16.2         Meeting   Long Trip

START_DATE*    datetime64[ns]
END_DATE*              object
CATEGORY*              object
START*                 object
STOP*                  object
MILES*                float64
PURPOSE*               object
Miles_cat              object
dtype: object

In [167]:
res=df.groupby(["START*"]).agg({"START_DATE*":["min","max"],"MILES*":"mean"})
res.reset_index(inplace=True)
res.columns =["START_CITY","EARLIST_TRIP","RECENT_TRIP","AVG_DIST"]
res

START_CITY        EARLIST_TRIP         RECENT_TRIP    AVG_DIST
0              Agnew 2016-11-04 21:04:00 2016-11-06 10:50:00    2.775000
1             Almond 2016-10-30 12:58:00 2016-10-30 12:58:00   15.200000
2               Apex 2016-01-29 21:21:00 2016-12-12 14:26:00    5.341176
3              Arabi 2016-06-25 10:50:00 2016-06-25 10:50:00   17.000000
4          Arlington 2016-08-02 11:51:00 2016-08-02 11:51:00    4.900000
..               ...                 ...                 ...         ...
170  West University 2016-03-10 14:39:00 2016-03-16 18:43:00    2.200000
171           Weston 2016-03-05 12:57:00 2016-06-05 15:57:00    4.000000
172   Westpark Place 2016-02-26 11:05:00 2016-11-03 14:13:00    2.182353
173      Whitebridge 2016-01-19 09:09:00 2016-11-03 13:42:00    4.020588
174    Winston Salem 2016-10-28 18:13:00 2016-10-28 18:13:00  133.600000

[175 rows x 4 columns]

In [169]:
res.to_csv("sub.csv")

# Loops and function

In [170]:
r=[]
temp=[1,2,3,4]
for i in temp:
    r.append(i*2)
r

[2, 4, 6, 8]

In [171]:
r=[i*i for i in temp]
r

[1, 4, 9, 16]

In [203]:
import pandas as pd
sales= pd.read_csv("store_sales .csv")

In [204]:
sales.head()

store_id        city  Jan  Feb  Mar  Apr  May  Jun  July  Aug  Sep  Oct  \
0      S_1       Texas    8   20   13   21   17   20    24   17   16    9   
1      S_2  California   12   19   15   15   11   19     7   15   10   11   
2      S_3  California   16   16   14   19   23    6    13   13   15   14   
3      S_4       Texas    8   18   13   10   14   14     6    8    8   18   
4      S_5       Texas   19    5   24    9    5   24    10    5   24   15   

   Nov  Dec  
0    7    6  
1   21   19  
2   24    8  
3    7   11  
4    6   13

In [205]:
sales.dtypes

store_id    object
city        object
Jan          int64
Feb          int64
Mar          int64
Apr          int64
May          int64
Jun          int64
July         int64
Aug          int64
Sep          int64
Oct          int64
Nov          int64
Dec          int64
dtype: object

In [208]:
sales["Jan"].mean()

14.46

# apply function

In [210]:
sales.apply("mean")

C:\Users\subit\AppData\Local\Temp\ipykernel_12700\1347439220.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  sales.apply("mean")


Jan     14.46
Feb     15.09
Mar     14.56
Apr     14.57
May     13.56
Jun     13.80
July    14.38
Aug     15.81
Sep     14.91
Oct     14.10
Nov     15.31
Dec     13.57
dtype: float64

In [211]:
sales.apply("mean",axis=1)

C:\Users\subit\AppData\Local\Temp\ipykernel_12700\395565985.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  sales.apply("mean",axis=1)


0     14.833333
1     14.500000
2     15.083333
3     11.250000
4     13.250000
        ...    
95    15.416667
96    12.833333
97    14.000000
98    14.416667
99    15.000000
Length: 100, dtype: float64

In [212]:
# important: can be used in case we want to ignore string type column
sales.select_dtypes(include =['int64',"float64"]).apply("mean")

Jan     14.46
Feb     15.09
Mar     14.56
Apr     14.57
May     13.56
Jun     13.80
July    14.38
Aug     15.81
Sep     14.91
Oct     14.10
Nov     15.31
Dec     13.57
dtype: float64

In [213]:
sales.groupby("city").agg('mean')

C:\Users\subit\AppData\Local\Temp\ipykernel_12700\2566535551.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  sales.groupby("city").agg('mean')


Jan        Feb        Mar        Apr        May        Jun  \
city                                                                           
Arizona     15.500000  15.272727  14.545455  14.954545  14.090909  15.090909   
California  14.744186  15.534884  14.627907  13.976744  13.255814  13.697674   
Texas       13.457143  14.428571  14.485714  15.057143  13.600000  13.114286   

                 July        Aug        Sep        Oct        Nov        Dec  
city                                                                          
Arizona     14.636364  15.500000  15.318182  14.954545  16.409091  13.318182  
California  14.813953  16.232558  14.883721  14.279070  15.279070  13.604651  
Texas       13.685714  15.485714  14.685714  13.342857  14.657143  13.685714

In [214]:
def add(a,b):
    res=a+b
    return res
add(3,4)

7

In [219]:
def bonus_function(sales_col):
    eligible_values = np.where(sales_col>10,"eligible","not eligible")
    return eligible_values
sales["Jan_bonus"]=bonus_function(sales["Jan"])
sales


store_id        city  Jan  Feb  Mar  Apr  May  Jun  July  Aug  Sep  Oct  \
0       S_1       Texas    8   20   13   21   17   20    24   17   16    9   
1       S_2  California   12   19   15   15   11   19     7   15   10   11   
2       S_3  California   16   16   14   19   23    6    13   13   15   14   
3       S_4       Texas    8   18   13   10   14   14     6    8    8   18   
4       S_5       Texas   19    5   24    9    5   24    10    5   24   15   
..      ...         ...  ...  ...  ...  ...  ...  ...   ...  ...  ...  ...   
95     S_96       Texas    7   10   20   20   10   15    15   21   15    7   
96     S_97  California   13    6    7   15   22   10    21   23   10    6   
97     S_98       Texas   16    9    6   14   20   13    11   10    8   22   
98     S_99     Arizona   18   16    9    5   12   22    11   13   21   17   
99    S_100  California    5   23   17   24   15   21    19   10   12   20   

    Nov  Dec     Jan_bonus  
0     7    6  not eligible  
1    21   19      eligible  
2    24    8      eligible  
3     7   11  not eligible  
4     6   13      eligible  
..  ...  ...           ...  
95   23   22  not eligible  
96   12    9      eligible  
97   17   22      eligible  
98   19   10      eligible  
99    5    9  not eligible  

[100 rows x 15 columns]

In [221]:
newdf=sales.select_dtypes(include=["int64","float64"]).apply(bonus_function)
newdf

Jan           Feb           Mar           Apr           May  \
0   not eligible      eligible      eligible      eligible      eligible   
1       eligible      eligible      eligible      eligible      eligible   
2       eligible      eligible      eligible      eligible      eligible   
3   not eligible      eligible      eligible  not eligible      eligible   
4       eligible  not eligible      eligible  not eligible  not eligible   
..           ...           ...           ...           ...           ...   
95  not eligible  not eligible      eligible      eligible  not eligible   
96      eligible  not eligible  not eligible      eligible      eligible   
97      eligible  not eligible  not eligible      eligible      eligible   
98      eligible      eligible  not eligible  not eligible      eligible   
99  not eligible      eligible      eligible      eligible      eligible   

             Jun          July           Aug           Sep           Oct  \
0       eligible      eligible      eligible      eligible  not eligible   
1       eligible  not eligible      eligible  not eligible      eligible   
2   not eligible      eligible      eligible      eligible      eligible   
3       eligible  not eligible  not eligible  not eligible      eligible   
4       eligible  not eligible  not eligible      eligible      eligible   
..           ...           ...           ...           ...           ...   
95      eligible      eligible      eligible      eligible  not eligible   
96  not eligible      eligible      eligible  not eligible  not eligible   
97      eligible      eligible  not eligible  not eligible      eligible   
98      eligible      eligible      eligible      eligible      eligible   
99      eligible      eligible  not eligible      eligible      eligible   

             Nov           Dec  
0   not eligible  not eligible  
1       eligible      eligible  
2       eligible  not eligible  
3   not eligible      eligible  
4   not eligible      eligible  
..           ...           ...  
95      eligible      eligible  
96      eligible  not eligible  
97      eligible      eligible  
98      eligible  not eligible  
99  not eligible  not eligible  

[100 rows x 12 columns]

In [223]:
pd.concat([sales,newdf])

store_id        city           Jan           Feb           Mar  \
0       S_1       Texas             8            20            13   
1       S_2  California            12            19            15   
2       S_3  California            16            16            14   
3       S_4       Texas             8            18            13   
4       S_5       Texas            19             5            24   
..      ...         ...           ...           ...           ...   
95      NaN         NaN  not eligible  not eligible      eligible   
96      NaN         NaN      eligible  not eligible  not eligible   
97      NaN         NaN      eligible  not eligible  not eligible   
98      NaN         NaN      eligible      eligible  not eligible   
99      NaN         NaN  not eligible      eligible      eligible   

             Apr           May           Jun      July           Aug  \
0             21            17            20        24            17   
1             15            11            19         7            15   
2             19            23             6        13            13   
3             10            14            14         6             8   
4              9             5            24        10             5   
..           ...           ...           ...       ...           ...   
95      eligible  not eligible      eligible  eligible      eligible   
96      eligible      eligible  not eligible  eligible      eligible   
97      eligible      eligible      eligible  eligible  not eligible   
98  not eligible      eligible      eligible  eligible      eligible   
99      eligible      eligible      eligible  eligible  not eligible   

             Sep           Oct           Nov           Dec     Jan_bonus  
0             16             9             7             6  not eligible  
1             10            11            21            19      eligible  
2             15            14            24             8      eligible  
3              8            18             7            11  not eligible  
4             24            15             6            13      eligible  
..           ...           ...           ...           ...           ...  
95      eligible  not eligible      eligible      eligible           NaN  
96  not eligible  not eligible      eligible  not eligible           NaN  
97  not eligible      eligible      eligible      eligible           NaN  
98      eligible      eligible      eligible  not eligible           NaN  
99      eligible      eligible  not eligible  not eligible           NaN  

[200 rows x 15 columns]

In [225]:
sub = pd.concat([sales,newdf],axis=1)
sub

store_id        city  Jan  Feb  Mar  Apr  May  Jun July Aug  ...  \
0       S_1       Texas    8   20   13   21   17   20   24  17  ...   
1       S_2  California   12   19   15   15   11   19    7  15  ...   
2       S_3  California   16   16   14   19   23    6   13  13  ...   
3       S_4       Texas    8   18   13   10   14   14    6   8  ...   
4       S_5       Texas   19    5   24    9    5   24   10   5  ...   
..      ...         ...  ...  ...  ...  ...  ...  ...  ...  ..  ...   
95     S_96       Texas    7   10   20   20   10   15   15  21  ...   
96     S_97  California   13    6    7   15   22   10   21  23  ...   
97     S_98       Texas   16    9    6   14   20   13   11  10  ...   
98     S_99     Arizona   18   16    9    5   12   22   11  13  ...   
99    S_100  California    5   23   17   24   15   21   19  10  ...   

             Mar           Apr           May           Jun          July  \
0       eligible      eligible      eligible      eligible      eligible   
1       eligible      eligible      eligible      eligible  not eligible   
2       eligible      eligible      eligible  not eligible      eligible   
3       eligible  not eligible      eligible      eligible  not eligible   
4       eligible  not eligible  not eligible      eligible  not eligible   
..           ...           ...           ...           ...           ...   
95      eligible      eligible  not eligible      eligible      eligible   
96  not eligible      eligible      eligible  not eligible      eligible   
97  not eligible      eligible      eligible      eligible      eligible   
98  not eligible  not eligible      eligible      eligible      eligible   
99      eligible      eligible      eligible      eligible      eligible   

             Aug           Sep           Oct           Nov           Dec  
0       eligible      eligible  not eligible  not eligible  not eligible  
1       eligible  not eligible      eligible      eligible      eligible  
2       eligible      eligible      eligible      eligible  not eligible  
3   not eligible  not eligible      eligible  not eligible      eligible  
4   not eligible      eligible      eligible  not eligible      eligible  
..           ...           ...           ...           ...           ...  
95      eligible      eligible  not eligible      eligible      eligible  
96      eligible  not eligible  not eligible      eligible  not eligible  
97  not eligible  not eligible      eligible      eligible      eligible  
98      eligible      eligible      eligible      eligible  not eligible  
99  not eligible      eligible      eligible  not eligible  not eligible  

[100 rows x 27 columns]

In [226]:
sub["Jan"]

Jan           Jan
0    8  not eligible
1   12      eligible
2   16      eligible
3    8  not eligible
4   19      eligible
..  ..           ...
95   7  not eligible
96  13      eligible
97  16      eligible
98  18      eligible
99   5  not eligible

[100 rows x 2 columns]

In [227]:
sub.columns

Index(['store_id', 'city', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'July',
       'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan_bonus', 'Jan', 'Feb', 'Mar',
       'Apr', 'May', 'Jun', 'July', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      dtype='object')

# missing data

In [241]:
years =[90,91,92,93,94,95]
f1 = {90:8, 91:9,92:10, 93:8, 94:9, 95:11}
firm1 = pd.Series(f1,index=years)
firm1
f2={90:14,93:9,94:5}
firm2=pd.Series(f2,index=years)
firm2
f3={93:10,94:12,95:13}
firm3 = pd.Series(f3,index=years)
firm3
df3=pd.DataFrame(columns=['Firm1','Firm2','Firm3'])
df3
df3.Firm1=firm1
df3.Firm2=firm2
df3.Firm3=firm3
df3

90     8
91     9
92    10
93     8
94     9
95    11
dtype: int64

90    14.0
91     NaN
92     NaN
93     9.0
94     5.0
95     NaN
dtype: float64

90     NaN
91     NaN
92     NaN
93    10.0
94    12.0
95    13.0
dtype: float64

Empty DataFrame
Columns: [Firm1, Firm2, Firm3]
Index: []

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92     10    NaN    NaN
93      8    9.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [235]:
firm2

90    14.0
91     NaN
92     NaN
93     9.0
94     5.0
95     NaN
dtype: float64

In [236]:
df3.dropna()

Firm1  Firm2  Firm3
93    8.0    9.0   10.0
94    9.0    5.0   12.0

In [237]:
df3

Firm1  Firm2  Firm3
90    8.0   14.0    NaN
91    9.0    NaN    NaN
92    NaN    NaN    NaN
93    8.0    9.0   10.0
94    9.0    5.0   12.0
95   11.0    NaN   13.0

In [242]:
cleandf3=df3.dropna(axis=1)
cleandf3

Firm1
90      8
91      9
92     10
93      8
94      9
95     11

In [245]:
# more NaN than specified thresh value, then drop that row
thresholddf=df3.dropna(axis=1,thresh=5)
print(thresholddf)
df3

    Firm1
90      8
91      9
92     10
93      8
94      9
95     11


Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92     10    NaN    NaN
93      8    9.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [246]:
fillna1=df3.fillna(0)
fillna1

Firm1  Firm2  Firm3
90      8   14.0    0.0
91      9    0.0    0.0
92     10    0.0    0.0
93      8    9.0   10.0
94      9    5.0   12.0
95     11    0.0   13.0

In [247]:
fillna1=df3.fillna(df3.mean())
fillna1

Firm1      Firm2      Firm3
90      8  14.000000  11.666667
91      9   9.333333  11.666667
92     10   9.333333  11.666667
93      8   9.000000  10.000000
94      9   5.000000  12.000000
95     11   9.333333  13.000000

# NumPy : Numerical Python

In [251]:
import numpy as np
distance =np.array([45,50,35])
speed = np.array([5,10,7])
time = distance//speed
time
type(time)

array([9, 5, 5])

numpy.ndarray

In [255]:
a=np.array([1,2,3,4,5])
b=np.array([10,20,30,40,50])
print(a+b)
type(a+b)

[11 22 33 44 55]


numpy.ndarray

In [258]:
a=np.array([1,2,3,"sds"])
a
a.dtype

array(['1', '2', '3', 'sds'], dtype='<U11')

dtype('<U11')

In [263]:
c=np.array(range(10))
c
d=np.arange(10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [264]:
arr=np.arange(5,56,5)
arr

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [266]:
# linspace(lowervalue, upper value, total value) 
# first value of the array created would be lower value last would upper value 
# and rest is calculate using the below formula . total value is len of array with 
# equal difference between them 
# calculated as (uppervalue-lower value)/(totalvalue -1)
space = np.linspace(1,10,30)
space

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

In [276]:
 data = np.array((32,42,34,56,23,67,86,89,56,76,45,34,98,89,78,67,56,12,21,32,87,98,76,98))
data
len(data)
# data2 =data.reshape(2,2,6) 
# 4 dimensional (2,2,6,1)
data2 = data.reshape(8,3)
data2
even_Data =(data2%2 ==0)
even_Data
data2[even_Data]

array([32, 42, 34, 56, 23, 67, 86, 89, 56, 76, 45, 34, 98, 89, 78, 67, 56,
       12, 21, 32, 87, 98, 76, 98])

24

array([[32, 42, 34],
       [56, 23, 67],
       [86, 89, 56],
       [76, 45, 34],
       [98, 89, 78],
       [67, 56, 12],
       [21, 32, 87],
       [98, 76, 98]])

array([[ True,  True,  True],
       [ True, False, False],
       [ True, False,  True],
       [ True, False,  True],
       [ True, False,  True],
       [False,  True,  True],
       [False,  True, False],
       [ True,  True,  True]])

array([32, 42, 34, 56, 86, 56, 76, 34, 98, 78, 56, 12, 32, 98, 76, 98])

In [277]:
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [278]:
np.zeros((3,5))+6

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [279]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [281]:
# identity matrix
np.eye(5)
np.eye(5,6)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [283]:
np.diag([1,3,5,3,4,5]) # fill the identity matrix with numbers

array([[1, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])